[general]
fontname=Hermit 12
selchars=-A-Za-z0-9,./?%&#:_
scrollback=1000
bgcolor=#000000000000
fgcolor=#d3d3d7d7cfcf
palette_color_0=#000000000000
palette_color_1=#cdcd00000000
palette_color_2=#4e4e9a9a0606
palette_color_3=#c4c4a0a00000
palette_color_4=#34346565a4a4
palette_color_5=#757550507b7b
palette_color_6=#060698989a9a
palette_color_7=#d3d3d7d7cfcf
palette_color_8=#555557575353
palette_color_9=#efef29292929
palette_color_10=#8a8ae2e23434
palette_color_11=#fcfce9e94f4f
palette_color_12=#72729f9fcfcf
palette_color_13=#adad7f7fa8a8
palette_color_14=#3434e2e2e2e2
palette_color_15=#eeeeeeeeecec
color_preset=Tango
disallowbold=false
cursorblinks=false
cursorunderline=true
audiblebell=false
tabpos=top
geometry_columns=80
geometry_rows=24
hidescrollbar=true
hidemenubar=true
hideclosebutton=false
hidepointer=false
disablef10=false
disablealt=false
disableconfirm=false

bgalpha=65535

[shortcut]
new_window_accel=<Primary><Shift>n
new_tab_accel=<Primary><Shift>t
close_tab_accel=<Primary><Shift>w
close_window_accel=<Primary><Shift>q
copy_accel=<Primary><Shift>c
paste_accel=<Primary><Shift>v
name_tab_accel=<Primary><Shift>i
previous_tab_accel=<Primary>Page_Up
next_tab_accel=<Primary>Page_Down
move_tab_left_accel=<Primary><Shift>Page_Up
move_tab_right_accel=<Primary><Shift>Page_Down
zoom_in_accel=<Primary><Shift>plus
zoom_out_accel=<Primary><Shift>underscore
zoom_reset_accel=<Primary><Shift>parenright
