base:
  pkg.latest:
    - pkgs:
      - nano
      - micro
      - git
      - sway
      - waybar
      - swaylock
      - lightdm
      - screen
      - curl
      - wget
      - nmap
      - htop
      - firefox-esr
      - unzip
      - neomutt
      - msmtp
      - lxterminal
      - lxappearance
      - gnome-tweaks
      - build-essential
