base:
  pkg.latest:
    - pkgs:
      - nano
      - micro
      - git
      - sway
      - swaybg
      - xwayland
      - waybar
      - wofi
      - swaylock
      - screen
      - curl
      - wget
      - nmap
      - htop
      - firefox-esr
      - unzip
      - neomutt
      - msmtp
      - open-vm-tools-desktop
      - build-essential
      - wob
      - pamixer
